name: ProgressPolygons
version: 'beta-0.1'
main: mplugin.net.bTEProgressPolygons.ProgressPolygons
api-version: '1.21'
authors: [ Dillsteamgamer ]

commands:
  getPolygonProgressTool:
    description: Give the player the tool used to make a polygon selection, also gives a standard message to the user for name format for polygons (configurable)
    permission: ProgressPolygons.make

  makeProgressPolygon:
    description: Creates a polygon at the current selection, takes an optional argument for a name
    permission: ProgressPolygons.make

  deleteProgressPolygon:
    description: Deletes a specific polygon, takes a mandatory ID argument, requires 2 person approval
    permission: ProgressPolygons.delete

  teleportProgressPolygon:
    description: Teleports the player to a specified polygon, takes a mandatory ID argument
    permission: ProgressPolygons.teleport

  getPolygonName:
    description: Takes the ID for a polygon and returns the name
    permission: ProgressPolygon.query

  getPolygonID:
    description: Takes the name for a polygon and returns all names and IDs that begin with that name
    permission: ProgressPolygon.query

  getNearbyPolygons:
    description: Shows the names and IDs of all polygons within a configurable range of the player (default a 1024x1024 square)
    permission: ProgressPolygon.query

  toggleProgressPolygonVisibility:
    description: Toggles whether the player can see the polygons, refreshes every configurable seconds
    permission: ProgressPolygon.see